// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateDistribution(arg1) {
  return window['go']['main']['App']['CalculateDistribution'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetAllProjects(arg1) {
  return window['go']['main']['App']['GetAllProjects'](arg1);
}

export function GetDashboardData(arg1, arg2) {
  return window['go']['main']['App']['GetDashboardData'](arg1, arg2);
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetWeeklyEntries(arg1) {
  return window['go']['main']['App']['GetWeeklyEntries'](arg1);
}

export function ToggleProjectActive(arg1) {
  return window['go']['main']['App']['ToggleProjectActive'](arg1);
}

export function UpdateActualHours(arg1) {
  return window['go']['main']['App']['UpdateActualHours'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
