// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function CalculateDistribution(arg1:models.CreateProjectInput):Promise<Array<models.WeeklyEntry>>;

export function CreateProject(arg1:models.CreateProjectInput):Promise<models.ProjectWithStats>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllProjects(arg1:boolean):Promise<Array<models.ProjectWithStats>>;

export function GetDashboardData(arg1:number,arg2:number):Promise<Array<main.DashboardWeekData>>;

export function GetDashboardSummary():Promise<main.DashboardSummary>;

export function GetProject(arg1:number):Promise<models.ProjectWithStats>;

export function GetWeeklyEntries(arg1:number):Promise<Array<models.WeeklyEntryWithStatus>>;

export function ToggleProjectActive(arg1:number):Promise<models.ProjectWithStats>;

export function UpdateActualHours(arg1:models.UpdateActualHoursInput):Promise<models.WeeklyEntryWithStatus>;

export function UpdateProject(arg1:models.UpdateProjectInput):Promise<models.ProjectWithStats>;
