// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {system} from '../models';
import {tracking} from '../models';
import {notes} from '../models';

export function CalculateDistribution(arg1:models.CreateProjectInput):Promise<Array<models.WeeklyEntry>>;

export function CreateBackup():Promise<string>;

export function CreateGoal(arg1:models.CreateGoalInput):Promise<models.Goal>;

export function CreateMeeting(arg1:models.CreateMeetingInput):Promise<models.Meeting>;

export function CreateNote(arg1:models.CreateNoteInput):Promise<models.Note>;

export function CreateProject(arg1:models.CreateProjectInput):Promise<models.ProjectWithStats>;

export function CreateProjectFromTemplate(arg1:system.CreateProjectFromTemplateInput):Promise<models.ProjectWithStats>;

export function CreateTask(arg1:models.CreateTaskInput):Promise<models.Task>;

export function CreateTemplate(arg1:number,arg2:string):Promise<system.ProjectTemplate>;

export function DeleteGoal(arg1:number):Promise<void>;

export function DeleteMeeting(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DeleteTemplate(arg1:number):Promise<void>;

export function ExportAllProjects():Promise<string>;

export function ExportProjectSummary(arg1:number):Promise<string>;

export function ExportWeeklyReport(arg1:string,arg2:string):Promise<string>;

export function GetAllProjects(arg1:boolean):Promise<Array<models.ProjectWithStats>>;

export function GetAllTasks(arg1:string,arg2:number):Promise<Array<models.TaskWithContext>>;

export function GetBackupInfo():Promise<system.BackupInfo>;

export function GetCapacityUtilization(arg1:string,arg2:string):Promise<Array<tracking.CapacityWeek>>;

export function GetDashboardData(arg1:number,arg2:number):Promise<Array<tracking.DashboardWeekData>>;

export function GetDashboardSummary():Promise<tracking.DashboardSummary>;

export function GetGoal(arg1:number):Promise<models.Goal>;

export function GetGoalStats(arg1:number):Promise<notes.GoalStats>;

export function GetGoals(arg1:number):Promise<Array<models.Goal>>;

export function GetMeeting(arg1:number):Promise<models.Meeting>;

export function GetMeetings(arg1:number):Promise<Array<models.Meeting>>;

export function GetMeetingsByDate(arg1:string):Promise<Array<models.MeetingWithProject>>;

export function GetMeetingsByWeek(arg1:string):Promise<Array<models.MeetingWithProject>>;

export function GetMonthlyTrends(arg1:number):Promise<Array<tracking.MonthlyTrend>>;

export function GetNote(arg1:number):Promise<models.Note>;

export function GetNotes(arg1:number):Promise<Array<models.Note>>;

export function GetProject(arg1:number):Promise<models.ProjectWithStats>;

export function GetTask(arg1:number):Promise<models.Task>;

export function GetTasksByProject(arg1:number):Promise<Array<models.Task>>;

export function GetTasksBySource(arg1:string,arg2:number):Promise<Array<models.Task>>;

export function GetTemplate(arg1:number):Promise<system.ProjectTemplate>;

export function GetTemplates():Promise<Array<system.ProjectTemplate>>;

export function GetVarianceReport(arg1:string,arg2:string):Promise<Array<tracking.VarianceReport>>;

export function GetWeeklyEntries(arg1:number):Promise<Array<models.WeeklyEntryWithStatus>>;

export function GetWeeklyEntriesByWeek(arg1:string):Promise<Array<models.WeeklyEntryWithProject>>;

export function PermanentlyDeleteProject(arg1:number):Promise<void>;

export function RestoreBackup():Promise<void>;

export function RestoreProject(arg1:number):Promise<models.ProjectWithStats>;

export function SearchGoals(arg1:string):Promise<Array<models.GoalWithProject>>;

export function SearchMeetings(arg1:string):Promise<Array<models.MeetingWithProject>>;

export function SearchNotes(arg1:string):Promise<Array<models.NoteWithProject>>;

export function SearchProjects(arg1:string):Promise<Array<models.ProjectWithStats>>;

export function SearchTasks(arg1:string):Promise<Array<models.TaskWithContext>>;

export function ToggleProjectActive(arg1:number):Promise<models.ProjectWithStats>;

export function UpdateActualHours(arg1:models.UpdateActualHoursInput):Promise<models.WeeklyEntryWithStatus>;

export function UpdateGoal(arg1:models.UpdateGoalInput):Promise<models.Goal>;

export function UpdateGoalStatus(arg1:number,arg2:string):Promise<models.Goal>;

export function UpdateMeeting(arg1:models.UpdateMeetingInput):Promise<models.Meeting>;

export function UpdateNote(arg1:models.UpdateNoteInput):Promise<models.Note>;

export function UpdateProject(arg1:models.UpdateProjectInput):Promise<models.ProjectWithStats>;

export function UpdateTask(arg1:models.UpdateTaskInput):Promise<models.Task>;

export function UpdateTaskStatus(arg1:number,arg2:string):Promise<models.Task>;
