// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateDistribution(arg1) {
  return window['go']['main']['App']['CalculateDistribution'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateMeeting(arg1) {
  return window['go']['main']['App']['CreateMeeting'](arg1);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProjectFromTemplate(arg1) {
  return window['go']['main']['App']['CreateProjectFromTemplate'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateTemplate'](arg1, arg2);
}

export function DeleteGoal(arg1) {
  return window['go']['main']['App']['DeleteGoal'](arg1);
}

export function DeleteMeeting(arg1) {
  return window['go']['main']['App']['DeleteMeeting'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportAllProjects() {
  return window['go']['main']['App']['ExportAllProjects']();
}

export function ExportProjectSummary(arg1) {
  return window['go']['main']['App']['ExportProjectSummary'](arg1);
}

export function ExportWeeklyReport(arg1, arg2) {
  return window['go']['main']['App']['ExportWeeklyReport'](arg1, arg2);
}

export function GetAllProjects(arg1) {
  return window['go']['main']['App']['GetAllProjects'](arg1);
}

export function GetAllTasks(arg1, arg2) {
  return window['go']['main']['App']['GetAllTasks'](arg1, arg2);
}

export function GetBackupInfo() {
  return window['go']['main']['App']['GetBackupInfo']();
}

export function GetCapacityUtilization(arg1, arg2) {
  return window['go']['main']['App']['GetCapacityUtilization'](arg1, arg2);
}

export function GetDashboardData(arg1, arg2) {
  return window['go']['main']['App']['GetDashboardData'](arg1, arg2);
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetGoal(arg1) {
  return window['go']['main']['App']['GetGoal'](arg1);
}

export function GetGoalStats(arg1) {
  return window['go']['main']['App']['GetGoalStats'](arg1);
}

export function GetGoals(arg1) {
  return window['go']['main']['App']['GetGoals'](arg1);
}

export function GetMeeting(arg1) {
  return window['go']['main']['App']['GetMeeting'](arg1);
}

export function GetMeetings(arg1) {
  return window['go']['main']['App']['GetMeetings'](arg1);
}

export function GetMeetingsByDate(arg1) {
  return window['go']['main']['App']['GetMeetingsByDate'](arg1);
}

export function GetMeetingsByWeek(arg1) {
  return window['go']['main']['App']['GetMeetingsByWeek'](arg1);
}

export function GetMonthlyTrends(arg1) {
  return window['go']['main']['App']['GetMonthlyTrends'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes(arg1) {
  return window['go']['main']['App']['GetNotes'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTasksByProject(arg1) {
  return window['go']['main']['App']['GetTasksByProject'](arg1);
}

export function GetTasksBySource(arg1, arg2) {
  return window['go']['main']['App']['GetTasksBySource'](arg1, arg2);
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetVarianceReport(arg1, arg2) {
  return window['go']['main']['App']['GetVarianceReport'](arg1, arg2);
}

export function GetWeeklyEntries(arg1) {
  return window['go']['main']['App']['GetWeeklyEntries'](arg1);
}

export function GetWeeklyEntriesByWeek(arg1) {
  return window['go']['main']['App']['GetWeeklyEntriesByWeek'](arg1);
}

export function PermanentlyDeleteProject(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteProject'](arg1);
}

export function RestoreBackup() {
  return window['go']['main']['App']['RestoreBackup']();
}

export function RestoreProject(arg1) {
  return window['go']['main']['App']['RestoreProject'](arg1);
}

export function SearchGoals(arg1) {
  return window['go']['main']['App']['SearchGoals'](arg1);
}

export function SearchMeetings(arg1) {
  return window['go']['main']['App']['SearchMeetings'](arg1);
}

export function SearchNotes(arg1) {
  return window['go']['main']['App']['SearchNotes'](arg1);
}

export function SearchProjects(arg1) {
  return window['go']['main']['App']['SearchProjects'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['main']['App']['SearchTasks'](arg1);
}

export function ToggleProjectActive(arg1) {
  return window['go']['main']['App']['ToggleProjectActive'](arg1);
}

export function UpdateActualHours(arg1) {
  return window['go']['main']['App']['UpdateActualHours'](arg1);
}

export function UpdateGoal(arg1) {
  return window['go']['main']['App']['UpdateGoal'](arg1);
}

export function UpdateGoalStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateGoalStatus'](arg1, arg2);
}

export function UpdateMeeting(arg1) {
  return window['go']['main']['App']['UpdateMeeting'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
